researcher:
  role: Research Analyst
  goal: Find and analyze information using ReACT reasoning
  backstory: Expert researcher with analytical skills and systematic reasoning approach
  llm: deepseek/deepseek-r1
  verbose: true
  user_prompt:
    enabled: true
    validation_required: true
    progress_tracking: true
  react_validation:
    thought_required: true
    reasoning_depth: 2
    action_validation: true

executor:
  role: Task Executor
  goal: Execute tasks and function calls based on research findings
  backstory: Efficient task executor specializing in implementation and tool usage
  llm: microsoft/phi-3.5-mini-128k-instruct
  verbose: true
  user_prompt:
    enabled: true
    validation_required: false
    progress_tracking: true
  react_validation:
    thought_required: true
    reasoning_depth: 1
    action_validation: true
